sudo: required 
services:
  - docker

before_install:
  - docker build -t koutilyagurjikindi/docker-react -f Dockerfile.dev .

script:
  - docker run koutilyagurjikindi/docker-react npm run test -- --coverage